name: Run Daily Script

on:
  schedule:
    - cron: "0 11 * * *"  # Roda todo dia às 03:00 UTC (00:00 no Brasil)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          npm install

      - name: Executar script
        run: node src/scrapper/scrapperTimerTest.js  