name: Run Daily Script

on:
  schedule:
    - cron: "0 11 * * *"  # Roda todo dia às 08:00 BRT (11:00 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar arquivo .env
        run: |
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
          echo "SIB_API_KEY=${{ secrets.SIB_API_KEY }}" >> .env
          echo "DESTINATION_EMAIL_1=${{ secrets.DESTINATION_EMAIL_1 }}" >> .env
          echo "DESTINATION_EMAIL_2=${{ secrets.DESTINATION_EMAIL_2 }}" >> .env

      - name: Instalar dependências
        run: npm install

      - name: Executar script
        run: node src/scrapper/scrapperTimerTest.js